[versions]
kotlin = "1.9.0"
paperweight = "1.5.6"
paper = "1.20.1-R0.1-SNAPSHOT"

[plugins]
kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
